/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationResult
 */
export interface AuthenticationResult {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResult
     */
    token?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationResult
     */
    successful?: boolean;
}

/**
 * Check if a given object implements the AuthenticationResult interface.
 */
export function instanceOfAuthenticationResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationResultFromJSON(json: any): AuthenticationResult {
    return AuthenticationResultFromJSONTyped(json, false);
}

export function AuthenticationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'successful': !exists(json, 'successful') ? undefined : json['successful'],
    };
}

export function AuthenticationResultToJSON(value?: AuthenticationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'successful': value.successful,
    };
}

