/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAllProductsModel } from './GetAllProductsModel';
import {
    GetAllProductsModelFromJSON,
    GetAllProductsModelFromJSONTyped,
    GetAllProductsModelToJSON,
} from './GetAllProductsModel';

/**
 * 
 * @export
 * @interface GetAllProductsModelIEnumerablePagedResponse
 */
export interface GetAllProductsModelIEnumerablePagedResponse {
    /**
     * 
     * @type {Array<GetAllProductsModel>}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    data?: Array<GetAllProductsModel> | null;
    /**
     * 
     * @type {string}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    status?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    errors?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllProductsModelIEnumerablePagedResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the GetAllProductsModelIEnumerablePagedResponse interface.
 */
export function instanceOfGetAllProductsModelIEnumerablePagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAllProductsModelIEnumerablePagedResponseFromJSON(json: any): GetAllProductsModelIEnumerablePagedResponse {
    return GetAllProductsModelIEnumerablePagedResponseFromJSONTyped(json, false);
}

export function GetAllProductsModelIEnumerablePagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllProductsModelIEnumerablePagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(GetAllProductsModelFromJSON)),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function GetAllProductsModelIEnumerablePagedResponseToJSON(value?: GetAllProductsModelIEnumerablePagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(GetAllProductsModelToJSON)),
        'message': value.message,
        'status': value.status,
        'errors': value.errors,
        'pageNumber': value.pageNumber,
        'pageSize': value.pageSize,
    };
}

