/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAllProductsModel } from './GetAllProductsModel';
import {
    GetAllProductsModelFromJSON,
    GetAllProductsModelFromJSONTyped,
    GetAllProductsModelToJSON,
} from './GetAllProductsModel';

/**
 * 
 * @export
 * @interface GetAllProductsModelResponse
 */
export interface GetAllProductsModelResponse {
    /**
     * 
     * @type {GetAllProductsModel}
     * @memberof GetAllProductsModelResponse
     */
    data?: GetAllProductsModel;
    /**
     * 
     * @type {string}
     * @memberof GetAllProductsModelResponse
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAllProductsModelResponse
     */
    status?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAllProductsModelResponse
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the GetAllProductsModelResponse interface.
 */
export function instanceOfGetAllProductsModelResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAllProductsModelResponseFromJSON(json: any): GetAllProductsModelResponse {
    return GetAllProductsModelResponseFromJSONTyped(json, false);
}

export function GetAllProductsModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllProductsModelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : GetAllProductsModelFromJSON(json['data']),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function GetAllProductsModelResponseToJSON(value?: GetAllProductsModelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetAllProductsModelToJSON(value.data),
        'message': value.message,
        'status': value.status,
        'errors': value.errors,
    };
}

