/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuidResponse
 */
export interface GuidResponse {
    /**
     * 
     * @type {string}
     * @memberof GuidResponse
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof GuidResponse
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GuidResponse
     */
    status?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GuidResponse
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the GuidResponse interface.
 */
export function instanceOfGuidResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuidResponseFromJSON(json: any): GuidResponse {
    return GuidResponseFromJSONTyped(json, false);
}

export function GuidResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function GuidResponseToJSON(value?: GuidResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'message': value.message,
        'status': value.status,
        'errors': value.errors,
    };
}

