/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductSold } from './ProductSold';
import {
    ProductSoldFromJSON,
    ProductSoldFromJSONTyped,
    ProductSoldToJSON,
} from './ProductSold';

/**
 * 
 * @export
 * @interface ProductSoldIEnumerableResponse
 */
export interface ProductSoldIEnumerableResponse {
    /**
     * 
     * @type {Array<ProductSold>}
     * @memberof ProductSoldIEnumerableResponse
     */
    data?: Array<ProductSold> | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSoldIEnumerableResponse
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductSoldIEnumerableResponse
     */
    status?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductSoldIEnumerableResponse
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the ProductSoldIEnumerableResponse interface.
 */
export function instanceOfProductSoldIEnumerableResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductSoldIEnumerableResponseFromJSON(json: any): ProductSoldIEnumerableResponse {
    return ProductSoldIEnumerableResponseFromJSONTyped(json, false);
}

export function ProductSoldIEnumerableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSoldIEnumerableResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ProductSoldFromJSON)),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function ProductSoldIEnumerableResponseToJSON(value?: ProductSoldIEnumerableResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ProductSoldToJSON)),
        'message': value.message,
        'status': value.status,
        'errors': value.errors,
    };
}

