/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Sale } from './Sale';
import {
    SaleFromJSON,
    SaleFromJSONTyped,
    SaleToJSON,
} from './Sale';

/**
 * 
 * @export
 * @interface SaleResponse
 */
export interface SaleResponse {
    /**
     * 
     * @type {Sale}
     * @memberof SaleResponse
     */
    data?: Sale;
    /**
     * 
     * @type {string}
     * @memberof SaleResponse
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SaleResponse
     */
    status?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SaleResponse
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the SaleResponse interface.
 */
export function instanceOfSaleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SaleResponseFromJSON(json: any): SaleResponse {
    return SaleResponseFromJSONTyped(json, false);
}

export function SaleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : SaleFromJSON(json['data']),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function SaleResponseToJSON(value?: SaleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SaleToJSON(value.data),
        'message': value.message,
        'status': value.status,
        'errors': value.errors,
    };
}

