/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Sale } from './Sale';
import {
    SaleFromJSON,
    SaleFromJSONTyped,
    SaleToJSON,
} from './Sale';

/**
 * 
 * @export
 * @interface ShopUser
 */
export interface ShopUser {
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    normalizedUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    normalizedEmail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShopUser
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    securityStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    concurrencyStamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShopUser
     */
    phoneNumberConfirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShopUser
     */
    twoFactorEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ShopUser
     */
    lockoutEnd?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShopUser
     */
    lockoutEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ShopUser
     */
    accessFailedCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof ShopUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ShopUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShopUser
     */
    lastName?: string | null;
    /**
     * 
     * @type {Array<Sale>}
     * @memberof ShopUser
     */
    sales?: Array<Sale> | null;
}

/**
 * Check if a given object implements the ShopUser interface.
 */
export function instanceOfShopUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShopUserFromJSON(json: any): ShopUser {
    return ShopUserFromJSONTyped(json, false);
}

export function ShopUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'normalizedUserName': !exists(json, 'normalizedUserName') ? undefined : json['normalizedUserName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'normalizedEmail': !exists(json, 'normalizedEmail') ? undefined : json['normalizedEmail'],
        'emailConfirmed': !exists(json, 'emailConfirmed') ? undefined : json['emailConfirmed'],
        'passwordHash': !exists(json, 'passwordHash') ? undefined : json['passwordHash'],
        'securityStamp': !exists(json, 'securityStamp') ? undefined : json['securityStamp'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'phoneNumberConfirmed': !exists(json, 'phoneNumberConfirmed') ? undefined : json['phoneNumberConfirmed'],
        'twoFactorEnabled': !exists(json, 'twoFactorEnabled') ? undefined : json['twoFactorEnabled'],
        'lockoutEnd': !exists(json, 'lockoutEnd') ? undefined : (json['lockoutEnd'] === null ? null : new Date(json['lockoutEnd'])),
        'lockoutEnabled': !exists(json, 'lockoutEnabled') ? undefined : json['lockoutEnabled'],
        'accessFailedCount': !exists(json, 'accessFailedCount') ? undefined : json['accessFailedCount'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'updatedBy': !exists(json, 'updatedBy') ? undefined : json['updatedBy'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'sales': !exists(json, 'sales') ? undefined : (json['sales'] === null ? null : (json['sales'] as Array<any>).map(SaleFromJSON)),
    };
}

export function ShopUserToJSON(value?: ShopUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userName': value.userName,
        'normalizedUserName': value.normalizedUserName,
        'email': value.email,
        'normalizedEmail': value.normalizedEmail,
        'emailConfirmed': value.emailConfirmed,
        'passwordHash': value.passwordHash,
        'securityStamp': value.securityStamp,
        'concurrencyStamp': value.concurrencyStamp,
        'phoneNumber': value.phoneNumber,
        'phoneNumberConfirmed': value.phoneNumberConfirmed,
        'twoFactorEnabled': value.twoFactorEnabled,
        'lockoutEnd': value.lockoutEnd === undefined ? undefined : (value.lockoutEnd === null ? null : value.lockoutEnd.toISOString()),
        'lockoutEnabled': value.lockoutEnabled,
        'accessFailedCount': value.accessFailedCount,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdBy': value.createdBy,
        'updatedBy': value.updatedBy,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'sales': value.sales === undefined ? undefined : (value.sales === null ? null : (value.sales as Array<any>).map(SaleToJSON)),
    };
}

