/* tslint:disable */
/* eslint-disable */
/**
 * Retail Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UnitMeasure = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11
} as const;
export type UnitMeasure = typeof UnitMeasure[keyof typeof UnitMeasure];


export function UnitMeasureFromJSON(json: any): UnitMeasure {
    return UnitMeasureFromJSONTyped(json, false);
}

export function UnitMeasureFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitMeasure {
    return json as UnitMeasure;
}

export function UnitMeasureToJSON(value?: UnitMeasure | null): any {
    return value as any;
}

